#!/usr/bin/env bash
set -euo pipefail

###############################################################################
# 0_config.sh — ATAC-seq upstream pipeline (fork of cutrun/0_config.sh)
#
# What's different from CUT&RUN
#   - Trim Galore uses Nextera/Tn5 adapters (TRIM_ADAPTER_PRESET="--nextera")
#   - bowtie2: -X $BT2_MAX_FRAG (2000) --no-mixed --no-discordant
#   - Post-alignment: name-sort + fixmate + coord-sort + markdup, then
#       MAPQ + flag + chrM filtering -> ${sample}_sorted.bam
#   - Tn5 shift via deeptools alignmentSieve --ATACshift -> ${sample}_sorted.shifted.bam
#       (used by HOMER tag dirs, peak callers, and bigWig generation)
#   - MACS3: --nomodel --shift -75 --extsize 150 --keep-dup all (forced for
#       both PE and SE per project decision; treats Tn5 cut sites individually)
#   - HOMER findPeaks: -style dnase, no control branch
#   - 5_qc adds TSS enrichment + bamPEFragmentSize; drops run_spp.R
###############################################################################

# ---- Base ----
BASE="${BASE:-${HOME}/work/seq/ATACseq/my_project}"

# ---- Conda env "bio" ----
CONDA_BIO_ENV="${CONDA_BIO_ENV:-${HOME}/miniforge3/envs/bio}"
if [[ -n "${CONDA_BIO_ENV}" && -d "${CONDA_BIO_ENV}/bin" ]]; then
  export PATH="${CONDA_BIO_ENV}/bin:${PATH}"
fi

# ---- Directories ----
RAW_DIR="${BASE}/data"
TRIM_DIR="${BASE}/cleandata"
ALIGN_DIR="${BASE}/align"
BAM_DIR="${ALIGN_DIR}/bam"
TRACK_DIR="${ALIGN_DIR}/track"
BAMQC_DIR="${BAM_DIR}/bamqc"
TAG_DIR="${ALIGN_DIR}/tags"
PEAK_DIR="${BASE}/peaks"
MACS3_DIR="${PEAK_DIR}/macs3"
HOMER_PEAK_DIR="${PEAK_DIR}/homer"
MULTIQC_OUT="${BASE}/multiqc"
LOG_DIR="${BASE}/logs"

# ---- Single-end mode ----
SE="${SE:-0}"

# ---- Step toggles ----
RUN_TRIM="${RUN_TRIM:-1}"
RUN_BOWTIE2="${RUN_BOWTIE2:-1}"
RUN_HOMER_TAGS="${RUN_HOMER_TAGS:-1}"
RUN_PEAK_MACS3="${RUN_PEAK_MACS3:-1}"
RUN_PEAK_HOMER="${RUN_PEAK_HOMER:-1}"
RUN_QC="${RUN_QC:-1}"

# ---- Trimming (1_trim_qc) ----
TRIM_ADAPTER_PRESET="${TRIM_ADAPTER_PRESET:---nextera}"   # Nextera/Tn5 ME adapter (CTGTCTCTTATA)
TRIM_STRINGENCY=5
TRIM_MIN_LENGTH=36
TRIM_QUAL=25
TRIM_CPU=8

# ---- Alignment (2_bowtie2) ----
BT2_CPU=12
BAMCOV_CPU=8
GENOME="hg38"
GENOME_INDEX="/mnt/share/archive/bkup/ref/align/bowtie2/${GENOME}_noalt/${GENOME}"
BT2_MAX_FRAG=2000                       # ATAC fragments span NFR -> tri-nucleosomal
BT2_EXTRA="${BT2_EXTRA:---no-mixed --no-discordant}"

# ---- Post-alignment filtering (2_bowtie2) ----
MAPQ_MIN=30                             # standard ENCODE ATAC threshold
EXCLUDE_FLAGS=1804                      # 1024 dup + 512 QCfail + 256 secondary + 8 mate-unmapped + 4 unmapped
EXCLUDE_CHROMS="chrM"                   # space-separated; e.g. "chrM chrEBV"
DELETE_MARKED_AFTER_BOWTIE2=0           # _marked.bam is needed by preseq in 5_qc; set 1 to drop after first pass

# ---- Tn5 shift (2_bowtie2) ----
TN5_SHIFT=1                             # alignmentSieve --ATACshift -> _sorted.shifted.bam

# ---- QC (5_qc) ----
QC_THREADS=8
BAMQC_REGION="chr19"
TSS_BED="${HOME}/work/ref/annot/${GENOME}/${GENOME}_tss.bed"      # auto-generated by 5_qc if missing
TSS_FLANK=2000                          # +/- bp around TSS for computeMatrix

# ---- Coverage / deepTools (2_bowtie2) ----
BINSIZE=10
GENOMESIZE=2913022398                   # hg38 effective genome size
NORMALIZE="RPGC"
IGNORE_CHR="chrM"

# ---- Space saving (2_bowtie2) ----
DELETE_TRIMMED_AFTER_ALIGN=1

# ---- Peak calling ----
PEAKCALL_GROUPS_FILE="${BASE}/peakcall_groups.tsv"
# Format unchanged from CUT&RUN: ip_bam<TAB>control_bam<TAB>name<TAB>type
# For ATAC: ip_bam should be ${sample}_sorted.shifted.bam; control_bam is "-"; type is informational.

BLACKLIST="${HOME}/work/ref/blacklist/${GENOME}/${GENOME}-blacklist.v2.bed"

# ---- MACS3 (4.1) — ATAC cut-site mode (forced for SE and PE) ----
MACS3_CMD="macs3"
MACS3_GENOMESIZE="hs"
MACS3_FDR=0.05
MACS3_FORMAT="${MACS3_FORMAT:-BAM}"     # treat each shifted read as a single cut site
MACS3_SHIFT=-75
MACS3_EXTSIZE=150
MACS3_KEEP_DUP="all"                    # dedup happened upstream; keep what's left

###############################################################################
# Helpers
###############################################################################
mkdir -p "$RAW_DIR" "$TRIM_DIR" "$ALIGN_DIR" "$BAM_DIR" "$TRACK_DIR" "$BAMQC_DIR" "$TAG_DIR" "$PEAK_DIR" "$MACS3_DIR" "$HOMER_PEAK_DIR" "$LOG_DIR" "$MULTIQC_OUT"

check_cmd() {
  local cmd="$1"
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "ERROR: Required command '$cmd' not found in PATH." >&2
    exit 1
  fi
}

check_cmd_string() {
  local cmdstr="$1"
  local first
  first="$(echo "$cmdstr" | awk '{print $1}')"
  if ! command -v "$first" >/dev/null 2>&1; then
    echo "ERROR: Required command '$first' not found in PATH (needed for: $cmdstr)" >&2
    exit 1
  fi
}

log_start() {
  local step="$1"
  local logfile="${LOG_DIR}/${step}_$(date +%Y%m%d_%H%M%S).log"
  echo "Logging to: $logfile"
  exec > >(tee -a "$logfile") 2>&1
}
