#!/usr/bin/env bash
# sync_brain.sh — sync the DURABLE Claude memory between this node's live memory
# dir and the git-tracked carry-bundle in the PRIVATE work_brain repo
# ($HOME/work/work_brain/memory/).
#
#   push : live  -> bundle   (feedback_* + user_* + reference_*, minus node-specific)
#   pull : bundle -> live     (durable set; leaves box-local project_* untouched)
#
# NOTE: push/pull are additive (cp-only) — renaming or superseding a synced
#       memory requires a manual `git rm` of the stale twin in the bundle.
#
# Filter (memory `type` taxonomy + PROVISION App-G):
#   feedback_*, user_*, reference_*  -> synced EXCEPT the node-specific facts below
#                                       (facts describing one machine, not the lab)
#   project_*                        -> never collected by push (box-local findings);
#                                       the 2 seeded project notes are pull-only.
set -euo pipefail
# durable-memory bundle lives in the PRIVATE work_brain repo (not public scripts/)
BUNDLE="${BRAIN_REPO:-$HOME/work/work_brain}/memory"
# live Claude memory dir; override with LIVE=... . Default = the per-project dir
# Claude Code uses for $HOME/work (path with '/' -> '-').
LIVE="${LIVE:-$HOME/.claude/projects/$(printf '%s' "$HOME/work" | sed 's#/#-#g')/memory}"

# memories that describe ONE machine (not the lab) — carried once as re-validate
# seeds, never auto-synced. This is the machine-specific subset of PROVISION
# App-G (not App-G verbatim), aligned with MEMORY.md's re-validate header.
NODE_SPECIFIC="reference_git_https_only reference_gh_binary_location reference_genome_fastas feedback_conda_env_build_linux01 feedback_cpu_cap_16 reference_linux01_vscode_clipboard_glibc"
is_node_specific() { case " $NODE_SPECIFIC " in *" $1 "*) return 0 ;; *) return 1 ;; esac; }

case "${1:-}" in
  push)
    [[ -d "$LIVE" ]] || { echo "live memory dir not found: $LIVE (set LIVE=...)"; exit 1; }
    mkdir -p "$BUNDLE"
    for f in "$LIVE"/feedback_*.md "$LIVE"/user_*.md "$LIVE"/reference_*.md; do
      [[ -e "$f" ]] || continue
      is_node_specific "$(basename "$f" .md)" || cp "$f" "$BUNDLE/"
    done
    # deterministically regenerate the bundle index from the exact set of *.md
    # now in $BUNDLE (sorted glob, one bullet/file, type from filename prefix).
    # Pure function of the file set -> every node produces an identical MEMORY.md.
    {
      echo "# MEMORY.md — durable carry-bundle index (auto-generated by sync_brain.sh push)"
      echo
      for m in "$BUNDLE"/*.md; do
        base="$(basename "$m")"
        [[ "$base" == "MEMORY.md" ]] && continue
        case "$base" in
          feedback_*)  type=feedback ;;
          user_*)      type=user ;;
          reference_*) type=reference ;;
          project_*)   type=project ;;
          *)           type=other ;;
        esac
        echo "- [$type] $base"
      done
    } > "$BUNDLE/MEMORY.md"
    echo "pushed durable memories -> $BUNDLE (regenerated MEMORY.md index)"
    echo "NOTE: review the diff, then commit (per-commit sign-off; no Co-Authored-By trailer)."
    ;;
  pull)
    [[ -d "$BUNDLE" ]] || { echo "bundle not found: $BUNDLE"; exit 1; }
    mkdir -p "$LIVE"
    for f in "$BUNDLE"/*.md; do
      base="$(basename "$f")"
      [[ "$base" == "MEMORY.md" ]] && continue
      # back up a live file that is NEWER than the bundle copy so an unpushed
      # live edit is not silently lost when the pull overwrites it
      if [[ -e "$LIVE/$base" && "$LIVE/$base" -nt "$f" ]]; then
        cp "$LIVE/$base" "$LIVE/$base.bak.$(date +%s)"
        echo "WARN: live $base newer than bundle — backed up before overwrite" >&2
      fi
      cp "$f" "$LIVE/"
    done
    echo "pulled durable memories -> $LIVE (box-local project_* left untouched)."
    echo "NOTE: merge $BUNDLE/MEMORY.md lines into $LIVE/MEMORY.md by hand so this"
    echo "      node's own project_* index lines are not clobbered."
    ;;
  *) echo "usage: sync_brain.sh {push|pull}   (LIVE=<memory dir> to override)"; exit 2 ;;
esac
